import { type CompatibilityManifest, defineCompatibility } from 'emulon';

const version = '2026-04-22.dahlia';
const auth = ['local-bearer-api-key'];

type Operation = CompatibilityManifest['operations'][number];

function api(
  id: string,
  method: Operation['method'],
  path: string,
  input: string[],
  output: string,
  cases: string[],
  events: string[] = [],
): Operation {
  return {
    id,
    method,
    path,
    surface: 'api',
    version,
    auth,
    input,
    output,
    events,
    cases,
  };
}

const list = ['limit', 'starting_after', 'ending_before', 'expand[]'];
const catalog = ['stripe.catalog.1'];
const discounts = ['stripe.discounts.1'];
const checkout = ['stripe.checkout.1'];
const payments = ['stripe.payments.1'];

export const compatibility: CompatibilityManifest = defineCompatibility({
  'schemaVersion': 1,
  'plugin': '@emulon/stripe',
  'provider': {
    'name': 'Stripe',
    'api': 'Customers, catalog, discounts, Checkout and payments',
  },
  'operations': [
    api(
      'customers.create',
      'POST',
      '/v1/customers',
      [
        'name',
        'email',
        'description',
        'phone',
        'metadata',
        'Idempotency-Key header',
      ],
      'Customer',
      ['stripe.customers.1'],
      ['customer.created'],
    ),
    api(
      'customers.get',
      'GET',
      '/v1/customers/:id',
      ['id'],
      'Customer',
      ['stripe.customers.1'],
    ),
    api(
      'products.create',
      'POST',
      '/v1/products',
      [
        'id',
        'name',
        'active',
        'description',
        'metadata',
        'tax_code',
        'statement_descriptor',
        'unit_label',
        'url',
      ],
      'Product',
      catalog,
    ),
    api(
      'products.get',
      'GET',
      '/v1/products/:id',
      ['id'],
      'Product',
      catalog,
    ),
    api(
      'products.update',
      'POST',
      '/v1/products/:id',
      [
        'name',
        'active',
        'description',
        'metadata',
        'tax_code',
        'default_price',
      ],
      'Product',
      catalog,
    ),
    api(
      'products.list',
      'GET',
      '/v1/products',
      ['active', 'ids', ...list],
      'List of products, newest first',
      catalog,
    ),
    api(
      'prices.create',
      'POST',
      '/v1/prices',
      [
        'product',
        'unit_amount',
        'currency',
        'lookup_key',
        'transfer_lookup_key',
        'active',
        'nickname',
        'tax_behavior',
        'metadata',
      ],
      'One-time Price',
      catalog,
    ),
    api(
      'prices.get',
      'GET',
      '/v1/prices/:id',
      ['id'],
      'Price',
      catalog,
    ),
    api(
      'prices.update',
      'POST',
      '/v1/prices/:id',
      [
        'active',
        'nickname',
        'lookup_key',
        'transfer_lookup_key',
        'tax_behavior',
        'metadata',
      ],
      'Price',
      catalog,
    ),
    api(
      'prices.list',
      'GET',
      '/v1/prices',
      ['active', 'product', 'currency', 'type', 'lookup_keys[]', ...list],
      'List of prices, newest first',
      catalog,
    ),
    api(
      'coupons.create',
      'POST',
      '/v1/coupons',
      [
        'id',
        'percent_off',
        'amount_off',
        'currency',
        'duration',
        'duration_in_months',
        'max_redemptions',
        'redeem_by',
        'name',
        'applies_to[products][]',
        'metadata',
      ],
      'Coupon',
      discounts,
    ),
    api(
      'coupons.get',
      'GET',
      '/v1/coupons/:id',
      ['id'],
      'Coupon',
      discounts,
    ),
    api(
      'coupons.delete',
      'DELETE',
      '/v1/coupons/:id',
      ['id'],
      'Deleted coupon',
      discounts,
    ),
    api(
      'promotion_codes.create',
      'POST',
      '/v1/promotion_codes',
      [
        'promotion[type]=coupon',
        'promotion[coupon]',
        'code',
        'active',
        'customer',
        'expires_at',
        'max_redemptions',
        'restrictions[first_time_transaction]',
        'restrictions[minimum_amount]',
        'restrictions[minimum_amount_currency]',
        'metadata',
        'expand[]',
      ],
      'PromotionCode with promotion.coupon',
      discounts,
    ),
    api(
      'promotion_codes.get',
      'GET',
      '/v1/promotion_codes/:id',
      ['id', 'expand[]'],
      'PromotionCode',
      discounts,
    ),
    api(
      'promotion_codes.update',
      'POST',
      '/v1/promotion_codes/:id',
      ['active', 'metadata', 'expand[]'],
      'PromotionCode',
      discounts,
    ),
    api(
      'promotion_codes.list',
      'GET',
      '/v1/promotion_codes',
      ['active', 'code', 'coupon', 'customer', ...list],
      'List of promotion codes, newest first',
      discounts,
    ),
    api(
      'checkout.sessions.create',
      'POST',
      '/v1/checkout/sessions',
      [
        'mode=payment',
        'line_items[][price]',
        'line_items[][quantity]',
        'customer',
        'customer_email',
        'customer_creation',
        'client_reference_id',
        'allow_promotion_codes',
        'discounts[][promotion_code]',
        'discounts[][coupon]',
        'success_url',
        'cancel_url',
        'expires_at',
        'locale',
        'payment_method_types[]',
        'ui_mode=hosted',
        'managed_payments[enabled]',
        'metadata',
      ],
      'Checkout Session with a local hosted url',
      checkout,
    ),
    api(
      'checkout.sessions.get',
      'GET',
      '/v1/checkout/sessions/:id',
      ['id', 'expand[]'],
      'Checkout Session',
      checkout,
    ),
    api(
      'checkout.sessions.list',
      'GET',
      '/v1/checkout/sessions',
      ['payment_intent', 'customer', 'status', ...list],
      'List of Checkout Sessions, newest first',
      checkout,
    ),
    api(
      'checkout.sessions.line_items',
      'GET',
      '/v1/checkout/sessions/:id/line_items',
      ['id', 'limit'],
      'List of line items',
      checkout,
    ),
    api(
      'checkout.sessions.expire',
      'POST',
      '/v1/checkout/sessions/:id/expire',
      ['id'],
      'Expired Checkout Session',
      checkout,
      ['checkout.session.expired'],
    ),
    {
      'id': 'checkout.page.get',
      'method': 'GET',
      'path': '/c/pay/:id',
      'surface': 'web',
      'version': version,
      'auth': ['unguessable-session-url'],
      'input': ['id'],
      'output': 'Local HTML payment page',
      'events': [],
      'cases': checkout,
    },
    {
      'id': 'checkout.page.pay',
      'method': 'POST',
      'path': '/c/pay/:id',
      'surface': 'web',
      'version': version,
      'auth': ['unguessable-session-url', 'form-token'],
      'input': ['action=pay|cancel', 'email', 'name', 'promotion_code'],
      'output': '303 to success_url with {CHECKOUT_SESSION_ID}, or cancel_url',
      'events': ['checkout.session.completed'],
      'cases': checkout,
    },
    api(
      'payment_intents.get',
      'GET',
      '/v1/payment_intents/:id',
      ['id', 'expand[]'],
      'Succeeded PaymentIntent with latest_charge',
      checkout,
    ),
    api(
      'charges.get',
      'GET',
      '/v1/charges/:id',
      ['id', 'expand[]'],
      'Charge',
      checkout,
    ),
    api(
      'refunds.create',
      'POST',
      '/v1/refunds',
      ['charge', 'payment_intent', 'amount', 'reason', 'metadata'],
      'Succeeded Refund',
      payments,
      ['charge.refunded'],
    ),
    api(
      'refunds.get',
      'GET',
      '/v1/refunds/:id',
      ['id'],
      'Refund',
      payments,
    ),
    api(
      'disputes.get',
      'GET',
      '/v1/disputes/:id',
      ['id'],
      'Dispute',
      payments,
    ),
  ],
  'versions': [
    {
      'id': version,
      'accepted': [version],
      'headers': ['stripe-version'],
      'missing': 'Select the instance account default',
      'unknown':
        '400 invalid_request_error for unknown or disabled versions before mutation',
    },
  ],
  'authentication': {
    'flows': [
      'local-bearer-api-key',
      'unguessable-session-url',
      'form-token',
    ],
    'keyFormats': ['sk_test_ opaque key'],
    'ownership':
      'One local account per instance; reset invalidates keys, sessions and page tokens.',
    'unsupported': [
      'HTTP Basic',
      'Live keys',
      'Real Stripe accounts',
      'Publishable keys',
    ],
  },
  'events': [
    {
      'id': 'customer.created',
      'providerName': 'customer.created',
      'version': version,
      'projection': 'Event envelope with data.object Customer',
      'cases': ['stripe.customers.1'],
    },
    {
      'id': 'checkout.session.completed',
      'providerName': 'checkout.session.completed',
      'version': version,
      'projection':
        'Event envelope with data.object Checkout Session (payment_intent set when paid)',
      'cases': checkout,
    },
    {
      'id': 'checkout.session.expired',
      'providerName': 'checkout.session.expired',
      'version': version,
      'projection': 'Event envelope with data.object Checkout Session',
      'cases': checkout,
    },
    {
      'id': 'charge.refunded',
      'providerName': 'charge.refunded',
      'version': version,
      'projection':
        'Event envelope with data.object Charge and previous_attributes amount_refunded, refunded',
      'cases': payments,
    },
    {
      'id': 'charge.dispute.created',
      'providerName': 'charge.dispute.created',
      'version': version,
      'projection': 'Event envelope with data.object Dispute',
      'cases': payments,
    },
    {
      'id': 'charge.dispute.closed',
      'providerName': 'charge.dispute.closed',
      'version': version,
      'projection':
        'Event envelope with data.object Dispute and previous_attributes status',
      'cases': payments,
    },
  ],
  'webhooks': {
    'signing':
      'Stripe-Signature: t=Unix seconds,v1=HMAC-SHA256 hex; literal UTF-8 secret',
    'id': 'Stable evt_ ID in the event envelope across retries and redelivery',
    'body': 'Exact serialized event snapshot bytes retained across attempts',
    'success': 'Any 2xx response',
    'retries':
      'Local sandbox approximation: 60s, 1h, 2h after failures; four attempts total; stop on success or disabled destination',
    'redelivery':
      'Manual after terminal state; unavailable while queued or in-flight',
    'recovery':
      'Interrupted in-flight sends become failed/unknown and require manual redelivery; queued retries resume on restart',
    'timeoutMs': 5000,
    'cases': ['stripe.webhooks.1', 'stripe.webhooks.2', 'stripe.webhooks.3'],
  },
  'capabilities': [
    'http',
    'authorization',
    'events',
    'webhooks',
    'reset',
  ],
  'limitations': [
    {
      'id': 'stripe.resources',
      'description':
        'Implemented: customers (create, retrieve), products, one-time prices, coupons, promotion codes, payment-mode hosted Checkout, payment intents and charges as Checkout produces them, refunds and disputes. Not implemented: subscriptions, invoices, recurring prices, price_data, embedded Checkout, Payment Element, Connect, test clocks, search and customer lists.',
    },
    {
      'id': 'stripe.checkout',
      'description':
        'Payment happens on the local hosted page or through checkout.sessions.complete; every payment succeeds. No card numbers, 3DS, declines, taxes, shipping, adaptive pricing or Managed Payments behavior: managed_payments is accepted and ignored. customer_creation defaults to if_required, so payment mode creates no Customer.',
    },
    {
      'id': 'stripe.disputes',
      'description':
        'Disputes are opened and closed through control commands, standing in for the card network. No evidence submission, withdrawals or balance transactions.',
    },
    {
      'id': 'stripe.events',
      'description':
        'Only the six declared event types are recorded; for example payment_intent.succeeded, charge.succeeded and refund.created are not.',
    },
    {
      'id': 'stripe.idempotency',
      'description':
        'Every POST honors Idempotency-Key. Concurrent same-key requests serialize and replay; only committed results are cached. Infrastructure failures roll back instead of caching 500s. Lazy expiry after 24 hours.',
    },
    {
      'id': 'stripe.webhooks',
      'description':
        'Retry timing is a local approximation, not the exact Stripe schedule. No ordering guarantee, automatic recovery of interrupted sends, public virtual time or manual resend while an automatic retry is queued.',
    },
  ],
  'verification': {
    'mode': 'official-client',
    'client': 'stripe@22.1.1',
    'suites': [{
      'path': 'packages/stripe/tests/webhook_cases.ts',
      'cases': ['stripe.webhooks.1', 'stripe.webhooks.2'],
    }, {
      'path': 'packages/stripe/tests/customers_test.ts',
      'cases': ['stripe.customers.1'],
    }, {
      'path': 'packages/stripe/tests/billing_cases.ts',
      'cases': [
        'stripe.catalog.1',
        'stripe.discounts.1',
        'stripe.checkout.1',
        'stripe.payments.1',
        'stripe.webhooks.3',
      ],
    }],
    'sources': [
      'https://www.npmjs.com/package/stripe/v/22.1.1',
      'https://docs.stripe.com/api/customers/create?api-version=2026-04-22.dahlia',
      'https://docs.stripe.com/api/products?api-version=2026-04-22.dahlia',
      'https://docs.stripe.com/api/prices?api-version=2026-04-22.dahlia',
      'https://docs.stripe.com/api/coupons?api-version=2026-04-22.dahlia',
      'https://docs.stripe.com/api/promotion_codes?api-version=2026-04-22.dahlia',
      'https://docs.stripe.com/api/checkout/sessions?api-version=2026-04-22.dahlia',
      'https://docs.stripe.com/api/refunds?api-version=2026-04-22.dahlia',
      'https://docs.stripe.com/api/disputes?api-version=2026-04-22.dahlia',
    ],
    'retrieved': '2026-09-23',
    'liveProviderCompared': false,
  },
});
